backend:
  name: github
  repo: shawnyudi888/laysun.3.1
  branch: main
  base_url: https://www.laysun.co
  auth_endpoint: /api/auth

media_folder: "public/uploads"
public_folder: "/uploads"
site_url: https://www.laysun.co

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
